# syntax=docker/dockerfile:1

FROM golang:latest as builder

# build flibgolite
COPY . /flibgolite
WORKDIR /flibgolite
RUN CGO_ENABLED=0 go build -ldflags "-s -w" ./cmd/flibgolite

FROM alpine:latest
COPY --from=builder /flibgolite/flibgolite /flibgolite/flibgolite

# expose ports
EXPOSE 8085

WORKDIR /flibgolite
# run command
ENTRYPOINT ["/flibgolite/flibgolite"]